language: ruby
rvm:
  - 2.0.0
script: bundle exec rake test
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change

branches: 
  only:
    - master
    - develop
